error: Imposible obtener los usuarios de la base de datos!
error: Imposible obtener los usuarios de la base de datos!
error: Imposible obtener los usuarios de la base de datos!
error: Imposible obtener los usuarios de la base de datos! Schema hasn't been registered for model "carts".
Use mongoose.model(name, schema) {"stack":"MissingSchemaError: Schema hasn't been registered for model \"carts\".\nUse mongoose.model(name, schema)\n    at Connection.model (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\connection.js:1218:13)\n    at _getModelFromConn (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:569:15)\n    at addModelNamesToMap (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:496:17)\n    at getModelsMapForPopulate (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:200:7)\n    at populate (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\model.js:4183:21)\n    at _populate (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\model.js:4143:5)\n    at C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\model.js:4115:5\n    at new Promise (<anonymous>)\n    at Function.populate (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\model.js:4114:10)\n    at model.Query._find (C:\\Users\\migration\\Desktop\\TP FINAL\\TP_Final_BackEnd\\BackEnd\\node_modules\\mongoose\\lib\\query.js:2347:20)"}
error: Imposible leer los productos de la base de datos!
error: Imposible leer los productos de la base de datos!
error: Imposible leer los productos de la base de datos!
error: Imposible leer los productos de la base de datos!
error: Imposible leer los productos de la base de datos!
error: Imposible leer los productos de la base de datos!
error: Imposible leer los productos de la base de datos!
error: Error al eliminar los usuarios sin actividad
error: Error al eliminar los usuarios sin actividad all_users is not defined {"stack":"ReferenceError: all_users is not defined\n    at deleteOldUsers (file:///C:/Users/migration/Desktop/TP%20FINAL/TP_Final_BackEnd/BackEnd/SRC/controllers/usersController.js:12:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///C:/Users/migration/Desktop/TP%20FINAL/TP_Final_BackEnd/BackEnd/SRC/routes/usersRouter.js:27:9"}
error: Error al eliminar los usuarios sin actividad
error: Error al eliminar los usuarios sin actividad
error: Error al eliminar los usuarios sin actividad
error: Error al eliminar los usuarios sin actividad
error: Error al eliminar los usuarios sin actividad
error: Error al eliminar los usuarios sin actividad
error: Error al enviar el correo de recuperación
error: Error al enviar el correo de recuperación config_vars is not defined {"stack":"ReferenceError: config_vars is not defined\n    at sendResetPSWEmail (file:///C:/Users/lezam/Desktop/Desaf%C3%ADos/Proyecto%20Final/BackEnd/SRC/controllers/usersController.js:87:18)\n    at file:///C:/Users/lezam/Desktop/Desaf%C3%ADos/Proyecto%20Final/BackEnd/SRC/routes/usersRouter.js:49:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
fatal: Error al conectarse a la DB:  bad auth : authentication failed {"code":8000,"codeName":"AtlasError","connectionGeneration":0,"errorResponse":{"code":8000,"codeName":"AtlasError","errmsg":"bad auth : authentication failed","ok":0},"ok":0,"stack":"MongoServerError: bad auth : authentication failed\n    at Connection.sendCommand (C:\\Users\\lezam\\Desktop\\Desafíos\\Proyecto Final\\BackEnd\\node_modules\\mongodb\\lib\\cmap\\connection.js:297:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Connection.command (C:\\Users\\lezam\\Desktop\\Desafíos\\Proyecto Final\\BackEnd\\node_modules\\mongodb\\lib\\cmap\\connection.js:325:26)\n    at async continueScramConversation (C:\\Users\\lezam\\Desktop\\Desafíos\\Proyecto Final\\BackEnd\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:131:15)\n    at async executeScram (C:\\Users\\lezam\\Desktop\\Desafíos\\Proyecto Final\\BackEnd\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:80:5)\n    at async ScramSHA1.auth (C:\\Users\\lezam\\Desktop\\Desafíos\\Proyecto Final\\BackEnd\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:39:16)\n    at async performInitialHandshake (C:\\Users\\lezam\\Desktop\\Desafíos\\Proyecto Final\\BackEnd\\node_modules\\mongodb\\lib\\cmap\\connect.js:101:13)\n    at async connect (C:\\Users\\lezam\\Desktop\\Desafíos\\Proyecto Final\\BackEnd\\node_modules\\mongodb\\lib\\cmap\\connect.js:19:9)"}
error: Error al encontrar el usuario, imposible conectar con la DB
error: Error al encontrar el usuario, imposible conectar con la DB
